theme: jekyll-theme-slate
title: "Estudio de Reproducibilidad: Imágenes de Desigualdad en Chile"
description: "Estudio de reproducibilidad del estudio Imágenes de Desigualdad en Chile como parte de un trabajo evaluativo para el curso de Ciencias Abiertas 2021"
